version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: infowijs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - book-store-postgresql-local:/var/lib/postgresql/data

volumes:
  book-store-postgresql-local:
